In [2]:
import torch
import torch.nn as nn

In [3]:
batch, sequence_length, embedding_dim = 20, 5, 10
embedding = torch.randn(batch, sequence_length, embedding_dim)
embedding

tensor([[[ 1.4095e+00,  1.2237e-01,  1.0494e+00,  2.5261e-01,  1.6535e+00,
           4.8603e-01,  7.9003e-02,  8.7014e-01, -1.9946e-01, -8.9036e-01],
         [-3.0712e-01, -1.0102e+00,  3.9045e-01,  3.6338e-01,  5.7016e-01,
           5.5245e-01, -1.0825e+00, -4.0557e-01,  7.8639e-01,  5.4237e-01],
         [-1.5648e+00,  2.1220e-01,  2.7672e-01, -5.4504e-01, -1.2974e-01,
           1.0516e+00, -5.2800e-01, -3.9418e-01,  1.6262e+00, -7.8576e-01],
         [ 2.2954e+00, -9.0411e-01, -9.8462e-01,  1.0800e-01,  7.5468e-01,
           2.9838e-01, -7.9949e-01,  8.9690e-01,  2.3490e+00,  1.4547e-01],
         [ 5.5369e-01,  2.0709e+00, -6.8159e-01, -2.0311e+00,  1.7413e+00,
          -2.7444e-01,  9.0586e-01,  8.1355e-01, -2.0298e+00,  4.3073e-01]],

        [[-4.3801e-01, -1.2974e+00, -3.2671e-01, -1.3906e-01,  7.2806e-01,
           1.9154e-01, -4.9349e-01, -1.0623e+00, -1.9811e-01, -1.2234e+00],
         [-3.7625e-02, -6.1641e-01, -1.6556e+00, -5.3198e-01, -1.9602e-01,
          -5.2574

In [4]:
first_setence_embedding = torch.concat([torch.ones(1, embedding_dim) * i for i in range(1, sequence_length + 1)])
first_setence_embedding

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [8]:
embedding[0] = first_setence_embedding

In [14]:
layer_norm = nn.LayerNorm((5,10))
normed_embedding = layer_norm(embedding)

In [15]:
normed_embedding[0]

tensor([[-1.4142e+00, -1.4142e+00, -1.4142e+00, -1.4142e+00, -1.4142e+00,
         -1.4142e+00, -1.4142e+00, -1.4142e+00, -1.4142e+00, -1.4142e+00],
        [-7.0711e-01, -7.0711e-01, -7.0711e-01, -7.0711e-01, -7.0711e-01,
         -7.0711e-01, -7.0711e-01, -7.0711e-01, -7.0711e-01, -7.0711e-01],
        [-1.6859e-07, -1.6859e-07, -1.6859e-07, -1.6859e-07, -1.6859e-07,
         -1.6859e-07, -1.6859e-07, -1.6859e-07, -1.6859e-07, -1.6859e-07],
        [ 7.0710e-01,  7.0710e-01,  7.0710e-01,  7.0710e-01,  7.0710e-01,
          7.0710e-01,  7.0710e-01,  7.0710e-01,  7.0710e-01,  7.0710e-01],
        [ 1.4142e+00,  1.4142e+00,  1.4142e+00,  1.4142e+00,  1.4142e+00,
          1.4142e+00,  1.4142e+00,  1.4142e+00,  1.4142e+00,  1.4142e+00]],
       grad_fn=<SelectBackward0>)